### ISSUE TITLE
Requesting Kind Help - Hope you can upload book.json

### ISSUE THREAD

**Issue by TheXeler** [Revxrsal/lamp-docs#1]
It is very difficult to access gitbook.io in my area, so I want to obtain an offline version of the document through gitbook build. However, I seem to be missing some plugins or dependencies. Can you please upload your book.json?
(Note:I am not sure if this is the reason, but bookjson seems to be the foundation of a book, and I was prompted during build that "unknown block tag: tabs")
Thank you for reading.English is not my native language and there may be grammar errors. If you don't want to do this, just close this issue.

**Comment by Revxrsal** [comment]
o/
I've printed the GitBook as a PDF. It should be viewable anywhere. You can get it from here: https://drive.google.com/file/d/1LVXATsXwWOm5edwm3EAccyoGnBqbJvLB/view?usp=sharing

**Comment by TheXeler** [comment]
Thanks very much
Edit:Can I distribute and disseminate this document under the terms of the GPL? I would like to upload it to a more general-purpose online storage space in my region (Google's services are also quite slow to access here).

**Comment by Revxrsal** [comment]
Yes, go ahead.
